# Generated by Django 4.0.3 on 2022-04-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_address_alter_company_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='company',
            new_name='company_id',
        ),
    ]
